apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
- namespace.yaml
- akv-tls-provider.yaml
- deployment.yaml
images:
- name: YOUR_ACR.azurecr.io/live/jettech/kube-webhook-certgen
  newName: acraks2kjtmssx7hcb4.azurecr.io/live/jettech/kube-webhook-certgen
- name: YOUR_ACR.azurecr.io/live/ingress-nginx/controller
  newName: acraks2kjtmssx7hcb4.azurecr.io/live/ingress-nginx/controller